$PROB
Kirouac 2017 MAPK pathway and tumour growth in BRAF(V600E) colorectal cancer

// Kirouac DC, Schaefer G, Chan J, et al. Clinical responses to ERK inhibition
// in BRAF(V600E)-mutant colorectal cancer predicted using a computational
// model. npj Syst Biol Appl 2017;3:14 (CC BY 4.0).
// 
// EGFR/RTK -> RAS -> BRAF/CRAF -> MEK -> ERK signalling with DUSP, Sprouty
// and MYC-type feedback (FB1-FB4), a PI3K/AKT arm, S6 driving a
// proliferation signal (TD1) and logistic tumour growth (CELLS, relative
// to baseline). Signalling states are algebraic (quasi-steady state);
// feedbacks, tumour and drug PK are ODEs.
// 
// Generated by tools/build_mapk.py from the published SimBiology SBML.
// Parameter defaults are the medians of the clinical virtual population
// (Table S10); parameters not in it take the Table S8 values.
// 
// Drugs (dose into): cetuximab mg IV (RTK1i_blood), vemurafenib mg PO
// (RAFi_gut), cobimetinib mg PO (MEKi_gut), GDC-0994 mg PO (ERKi_gut).
// Units: time in days.

$PARAM @annotated
RASb     : 0.0499611563713624     : RAS_min
RASt     : 1.47542629609742       : RAS_max
k1       : 0.75                   : RTK1 -> RAS
tau1     : 0.5                    : RTK1 -> RAS
k3       : 2.23071013072619       : CRAF+BRAF -> MEK
tau3     : 0.671868475422854      : CRAF+BRAF -> MEK
MEKt     : 1.00957763552316       : MEK_max
MEKb     : 0.00920194437597321    : MEK_min
k2       : 0.1                    : RAS ->BRAF
tau2     : 2.32498060514752       : RAS ->BRAF
ERKb     : 0.0                    : ERK_min
ERKt     : 1.0                    : ERK_max
k4       : 2.60911533743242       : MEK ->ERK
kFB1     : 0.1                    : ERK -> ERK feedback (DUSP)
tauFB1   : 10.0                   : ERK -> ERK feedback (DUSP)
tau4     : 0.1                    : MEK ->ERK
S6b      : 0.0                    : S6_min
S6t      : 1.0                    : S6_max
k6       : 3.0                    : ERK+AKT -> S6
tau6     : 0.1                    : ERK+AKT -> S6
k5       : 2.74625276959909       : RAS ->CRAF
tau5     : 0.408684956863014      : RAS ->CRAF
Vmax     : 12.0                   : Max Cell Number
dmax     : 0.0403166139390134     : death rate
kg       : 0.468373390950471      : TD1 -> umax (growth reg)
taug     : 0.24147937407142       : TD1 -> umax (growth reg)
umax     : 0.075                  : max cell prolif (TD1 regulated)
wOR      : 1.0                    : wERK for ERK+AKT -> S6
AKTb     : 0.0                    : AKT_min
AKTt     : 1.0                    : AKT_max
k8       : 1.0                    : PI3K ->AKT
tau8     : 0.25                   : PI3K ->AKT
PI3Kb    : 0.0501337305069888     : PI3K_min
PI3Kt    : 1.0                    : PI3K_max
k7       : 1.0                    : RAS -> PI3K
tau7     : 0.25                   : RAS -> PI3K
ki1      : 1.0                    : EGFRi -|RTK1
taui1    : 0.0304                 : EGFRi -|RTK1 (mg/L)
ki2      : 2.0                    : RAFi -|BRAF
taui2    : 0.028338973068008      : RAFi -|BRAF (mg/L0
kFB2     : 0.43605102287761       : ERK -> RAS feedback (SPRY)
tauFB2   : 0.348731219207761      : ERK -> RAS feedback (SPRY)
kFB3     : 2.97523174161686       : ERK ->RTK feedback
ki4      : 0.65                   : ERKi -|ERK
tauFB3   : 0.1                    : ERK ->RTK feedback
taui4    : 0.0254685390862943     : ERKi -|ERK (mg/L)
BRAFb    : 0.9                    : BRAF_min
BRAFt    : 0.98195511203774       : BRAF_max
CRAFb    : 0.0                    : CRAF_min
CRAFt    : 0.999032538054214      : CRAF_max
ki3      : 0.65                   : MEKi -|MEK
taui3    : 0.000779558945636811   : MEKi -|MEK (mg/L)
G13      : 0.485487556441356      : Gain_RTK1(FB3~ERK)
G23      : 0.0                    : Gain_RTK2(FB3~ERK)
RTK2b    : 0.0                    : RTK2_min (MAPK-activating)
RTK2t    : 0.0986967814208809     : RTK2_max (MAPK-activating)
ki5      : 1.0                    : AKTi -|AKT
taui5    : 1.0                    : AKTi -|AKT (mg/L)
G14      : 0.0                    : Gain_RTK1(FB4~AKT)
RTK1b    : 0.0                    : RTK1_min (EGFR)
RTK1t    : 0.266438946040108      : RTK1_max (EGFR)
kFB4     : 2.0                    : AKT ->RTK feedback (FOXO)
tauFB4   : 0.1                    : AKT ->RTK feedback (FOXO)
G24      : 0.0                    : Gain_RTK2(FB4~AKT)
F1       : 1.0                    : EGFRi Bioavailable Fraction
V1       : 4.5                    : EGFRi Vdist
ka1      : 1.0                    : EGFRi absorption
ke1      : 0.148531538691417      : EGFRi clearance
p1       : 1.0                    : EGFRi Partition Coeff
G33      : 0.0                    : Gain_RTK3(FB3~ERK)
G34      : 0.0                    : Gain_RTK3(FB4~AKT)
RTK3b    : 0.0                    : RTK3_min (PI3K-activating)
F2       : 1.0                    : BRAFi Bioavailable Fraction
V2       : 114.0                  : BRAFi Vdist
ka2      : 4.5                    : BRAFi absorption
ke2      : 0.282456140350877      : BRAFi clearance
F3       : 1.0                    : MEKi Bioavailable Fraction
V3       : 487.0                  : MEKi Vdist
ka3      : 33.0                   : MEKi absorption
ke3      : 0.63013698630137       : MEKi clearance
p2       : 1.0                    : BRAFi Partition Coeff
p3       : 1.0                    : MEKi Partition Coeff
F4       : 1.0                    : ERKi Bioavailable Fraction
V4       : 171.0                  : ERKi Vdist
ka4      : 35.0                   : ERKi absorption
ke4      : 0.882162162162162      : ERKi clearance
p4       : 1.0                    : ERKi Partition Coeff
wRAS     : 0.895183982701171      : wRAS for RTK3 + RAS ->PI3K
RTK3t    : 0.0                    : RTK3_max (PI3K-activating)
F5       : 1.0                    : AKTi Bioavailable Fraction
V5       : 1.0                    : AKTi Vdist
ka5      : 1.0                    : AKTi absorption
ke5      : 1.0                    : AKTi clearance
p5       : 1.0                    : AKTi Partition Coeff
r4       : 1.0                    : AKT ->RTK feedback rate (FOXO)
r2       : 1.16772584318302       : ERK -> RAS feedback rate (SPRY)
r3       : 0.959576785194647      : ERK ->RTK feedback rate
r1       : 3.43598989683441       : ERK -> ERK feedback rate(DUSP)
q2       : 210.0                  : MEKi blood-V3 rate
V3b      : 295.0                  : MEKi Vdist_comp3
r5       : 10.0                   : S6 - TD1 - Growth Delay rate
Gdusp    : 0.507052214082698      : Gain_DUSP (FB1: ERK-ERK)
Gspry    : 0.463490989390342      : Gain_SPRY (FB2: ERK-RAS)

$INIT @annotated
TD1          : 1.0  : time delay: S6-growth
CELLS        : 1.0  : CELLS
FB1          : 0.7  : ERK -> ERK feedback
FB2          : 0.7  : ERK -> RAS feedback
FB3          : 0.7  : ERK ->RTK feedback
FB4          : 0.7  : AKT ->RTK feedback
RTK1i_blood  : 0.0  : EGFR inhibitor (blood)
RAFi_gut     : 0.0  : BRAF inhibitor (gut)
RAFi_blood   : 0.0  : BRAF inhibitor (blood)
MEKi_gut     : 0.0  : MEK inhibitor (gut)
MEKi_blood   : 0.0  : MEK inhibitor (blood)
ERKi_gut     : 0.0  : ERK inhibitor (gut)
ERKi_blood   : 0.0  : ERK inhibitor (blood)
AKTi_gut     : 0.0  : AKT inhibitor (gut)
AKTi_blood   : 0.0  : AKT inhibitor (blood)
MEKi_V3      : 0.0  : MEK inhibitor (V3)
RTK1i_gut    : 0.0  : EGFR inhibitor (gut)

$GLOBAL
#define hill(x, k, tau) (pow(fmax(0.0, x), k) / (pow(tau, k) + pow(fmax(0.0, x), k)))

$ODE
double RTK2 = (RTK2b + ((RTK2t - RTK2b) * (1.0 - (G23 * hill(FB3, kFB3, tauFB3))) * (1.0 - (G24 * hill(FB4, kFB4, tauFB4)))));
double RTK3 = (RTK3b + ((RTK3t - RTK3b) * (1.0 - (G33 * hill(FB3, kFB3, tauFB3))) * (1.0 - (G34 * hill(FB4, kFB4, tauFB4)))));
double RTK1i_C = (RTK1i_blood / V1);
double RAFi_C = (RAFi_blood / V2);
double MEKi_C = (MEKi_blood / V3);
double ERKi_C = (ERKi_blood / V4);
double AKTi_C = (AKTi_blood / V5);
double RTK1i = (p1 * RTK1i_C);
double RAFi = (p2 * RAFi_C);
double MEKi = (p3 * MEKi_C);
double ERKi = (p4 * ERKi_C);
double AKTi = (p5 * AKTi_C);
double RTK1 = ((RTK1b + ((RTK1t - RTK1b) * (1.0 - (G13 * hill(FB3, kFB3, tauFB3))) * (1.0 - (G14 * hill(FB4, kFB4, tauFB4))))) * (1.0 - hill(RTK1i, ki1, taui1)));
double RAS = ((RASb + ((RASt - RASb) * hill((RTK1 + RTK2), k1, tau1))) * (1.0 - (Gspry * hill(FB2, kFB2, tauFB2))));
double BRAF = ((BRAFb + ((BRAFt - BRAFb) * hill(RAS, k2, tau2))) * (1.0 - hill(RAFi, ki2, taui2)));
double PI3K = (PI3Kb + ((PI3Kt - PI3Kb) * hill((RTK3 + (wRAS * RAS)), k7, tau7)));
double CRAF = (CRAFb + ((CRAFt - CRAFb) * hill(RAS, k5, tau5)));
double MEK = ((MEKb + ((MEKt - MEKb) * hill((BRAF + CRAF), k3, tau3))) * (1.0 - hill(MEKi, ki3, taui3)));
double ERK = ((ERKb + ((ERKt - ERKb) * hill(MEK, k4, tau4))) * (1.0 - (Gdusp * hill(FB1, kFB1, tauFB1))) * (1.0 - hill(ERKi, ki4, taui4)));
double AKT = ((AKTb + ((AKTt - AKTb) * hill(PI3K, k8, tau8))) * (1.0 - hill(AKTi, ki5, taui5)));
double S6 = (S6b + ((S6t - S6b) * hill(((wOR * ERK) + ((1.0 - wOR) * AKT)), k6, tau6)));

double v_fb1 = (r1 * (ERK - FB1));
double v_fb2 = (r2 * (ERK - FB2));
double v_fb3 = (r3 * (ERK - FB3));
double v_TD = (r5 * (S6 - TD1));
double v_cell_growth = (((umax * hill(TD1, kg, taug)) - dmax) * CELLS * (1.0 - (CELLS / Vmax)));
double v_fb4 = (r4 * (AKT - FB4));
double v_PK1a_RAFi = (ka2 * F2 * RAFi_gut);
double v_PK1a_MEKi = (ka3 * F3 * MEKi_gut);
double v_PK1a_ERKi = (ka4 * F4 * ERKi_gut);
double v_PK1a_AKTi = (ka5 * F5 * AKTi_gut);
double v_PK2_RTK1i = (ke1 * RTK1i_blood);
double v_PK2_RAFi = (ke2 * RAFi_blood);
double v_PK2_MEKi = (ke3 * MEKi_blood);
double v_PK2_ERKi = (ke4 * ERKi_blood);
double v_PK2_AKTi = (ke5 * AKTi_blood);
double v_PK3_MEKi = (((q2 / V3) * MEKi_blood) - ((q2 / V3b) * MEKi_V3));
double v_PK1a_RTK1i = (ka1 * F1 * RTK1i_gut);
double v_PK1b_RTK1i = (ka1 * (1.0 - F1) * RTK1i_gut);
double v_PK1b_RAFi = (ka2 * (1.0 - F2) * RAFi_gut);
double v_PK1b_MEKi = (ka3 * (1.0 - F3) * MEKi_gut);
double v_PK1b_ERKi = (ka4 * (1.0 - F4) * ERKi_gut);
double v_PK1b_AKTi = (ka5 * (1.0 - F5) * AKTi_gut);

dxdt_TD1 = v_TD;
dxdt_CELLS = v_cell_growth;
dxdt_FB1 = v_fb1;
dxdt_FB2 = v_fb2;
dxdt_FB3 = v_fb3;
dxdt_FB4 = v_fb4;
dxdt_RTK1i_blood = -v_PK2_RTK1i + v_PK1a_RTK1i;
dxdt_RAFi_gut = -v_PK1a_RAFi - v_PK1b_RAFi;
dxdt_RAFi_blood = v_PK1a_RAFi - v_PK2_RAFi;
dxdt_MEKi_gut = -v_PK1a_MEKi - v_PK1b_MEKi;
dxdt_MEKi_blood = v_PK1a_MEKi - v_PK2_MEKi - v_PK3_MEKi;
dxdt_ERKi_gut = -v_PK1a_ERKi - v_PK1b_ERKi;
dxdt_ERKi_blood = v_PK1a_ERKi - v_PK2_ERKi;
dxdt_AKTi_gut = -v_PK1a_AKTi - v_PK1b_AKTi;
dxdt_AKTi_blood = v_PK1a_AKTi - v_PK2_AKTi;
dxdt_MEKi_V3 = v_PK3_MEKi;
dxdt_RTK1i_gut = -v_PK1a_RTK1i - v_PK1b_RTK1i;

$CAPTURE
RTK1i_C RAFi_C MEKi_C ERKi_C RTK1 RAS BRAF MEK ERK AKT S6
