$PROB
CD20xCD3 T-cell engager (mosunetuzumab): T-cell activation, B-cell killing and IL-6

// Hosseini I, Gadkar K, Stefanich E, Li CC, Sun LL, Chu YW, Ramanujan S.
// Mitigating the risk of cytokine release syndrome in a Phase I trial of
// CD20/CD3 bispecific antibody mosunetuzumab in NHL: impact of translational
// system modeling. npj Syst Biol Appl 2020;6:28 (open access).
//
// GENERATED by tools/build_tce.py from the authors' SimBiology project
// (Supplementary Software, TDBr26_6_paper.sbproj). Do not edit by hand.
//
// A bispecific antibody bridges CD3 on T cells and CD20 on B cells. T cells
// are activated in proportion to drug concentration and to the local B:T
// ratio, activated T cells kill B cells, proliferate, and die by
// activation-induced cell death; activated cells return to a post-activated
// state that can be reactivated. Each dose also causes transient T-cell
// margination out of blood (injection and drug effects). IL-6 is produced by
// activated T cells engaging B cells, so the first dose - when B cells are
// plentiful - drives the cytokine peak; step-up dosing depletes B cells at a
// low dose first. Compartments: peripheral blood (pb), spleen (tiss), lymph
// nodes (tiss2), bone marrow (tiss3, with CD19+CD20- precursors), and an
// optional tumour (tumor_on).
//
// Parameters: base project values with the variants activated in the
// authors' MainRun_Par_paper.m (5, 9, 11, 13, 14, 20, 24, 27), human physiology and human linear PK;
// checked against Supplementary Table 2 (human column) by the builder.
// kIL6prod was calibrated in cynomolgus monkeys only, so IL-6 is best read
// relative to its own peak. Rituximab, blinatumomab, subcutaneous dosing and
// BAFF are left out.
//
// Units: time day; cells (per compartment); drug amount ug/kg (dose TDBc_ugperkg,
// IV bolus), concentrations ug/mL. Give injection_effect and drug_effect an
// amount of 1 with every dose.

$PARAM
act0on = 1.0
B19no20_B1920_ratio = 0.25
Bcell_tumor_trafficking_on = 1.0
Bpbo_perml = 500000.0
Bpbref_perml = 500000.0
BW = 3.4
Cl_tdb = 5.4
Cld_tdb = 24.17
depleteBpb = 0.0
depleteTpb = 0.0
fa0 = 0.002
fAICD = 1.497
fapop_v24 = 1.0
fBexit = 0.333
fBkill = 0.1
fBprolif = 0.0
fBtissue3_v1 = 1.0
fdrug = 6.3839
finj = 1.0
fKmTB_kill = 10.0
fTa0apop = 2.019
fTa0deact = 0.001
fTact = 0.25
fTadeact = 0.005
fTap = 3.773
fTaprolif = 2.106
fTgenbl = 0.0
fTrapop = 0.2
IL6_tiss_contribution = 0.003
kBapop = 0.02
kBapop_cll = 1.0
kBkill = 275.189
kBmat_kBapop_ratio = 0.25
KBp = 333.0
KBp2 = 190.0
KBp3 = 80.0
kBprolif = 0.05
KBptumor = 1.0
kBtiss3exit = 0.041
kBtumorprolif = 0.025
KdrugactT = 130.083
KdrugactT_blin = 0.1
KdrugB = 1.302
KdrugB_blin = 0.015
kIL6prod = 1.0
Km_tdb = 5.72
KmBT_act = 0.716
KmBT_act_blin = 0.716
Kmkill_rtx = 25.0
KmTB_kill = 0.75
KmTB_kill_blin = 0.75
Kp = 0.14
Kp2 = 0.07
Kp3 = 0.07
Kptumor = 1.0
kTaapop = 0.061
kTact = 9.828
kTaexit = 0.123
kTgen = 1.0
kTprolif = 0.7
kTrexit = 0.045
KTrp = 200.0
KTrp2 = 190.0
KTrp3 = 60.0
KTrptumor = 1.0
ndrugactT = 0.8
ndrugactT_blin = 1.0
nkill = 1.027
nkill_blin = 1.027
S = 1.4
thalfIL6 = 20.0
tinjhalf = 1.0
tissue1on = 1.0
tissue2on = 1.0
tissue3on = 1.0
Trpbo_perml = 500000.0
Trpbref_perml = 500000.0
tumor_on = 0.0
Vc_tdb = 36.78
Vm_tdb = 0.0
VmB = 0.95
VmT = 0.9
Vp_tdb = 173.47
Vpb = 5000.0
Vtissue = 210.0
Vtissue2 = 400.0
Vtissue3 = 500.0
Vtumor = 1.0

$CMT Btiss restTtiss actTtiss TDBc_ugperkg TDBp_ugperkg restTpb Bpb actTpb act0Tpb act0Ttiss injection_effect act0Ttiss2 restTtiss2 actTtiss2 Btiss2 drug_effect B19no20tiss3 B1920tiss3 restTtiss3 act0Ttiss3 actTtiss3 restTtumor act0Ttumor actTtumor Btumor IL6pb IL6tiss IL6tiss2 IL6tiss3 IL6tumor

$MAIN
Btiss_0 = ((KBp * Bpbo_perml) * Vtissue);
restTtiss_0 = ((KTrp * Trpbo_perml) * Vtissue);
restTpb_0 = (((1.0 - depleteTpb) * Trpbo_perml) * Vpb);
Bpb_0 = (((1.0 - depleteBpb) * Bpbo_perml) * Vpb);
restTtiss2_0 = ((KTrp2 * Trpbo_perml) * Vtissue2);
Btiss2_0 = ((KBp2 * Bpbo_perml) * Vtissue2);
B19no20tiss3_0 = (((Bpbref_perml * KBp3) * B19no20_B1920_ratio) * Vtissue3);
B1920tiss3_0 = ((Bpbref_perml * KBp3) * Vtissue3);
restTtiss3_0 = ((KTrp3 * Trpbo_perml) * Vtissue3);
restTtumor_0 = ((KTrptumor * Trpbo_perml) * Vtumor);
Btumor_0 = ((KBptumor * Bpbo_perml) * Vtumor);

$ODE
double B1920Trratio_tiss3 = (B1920tiss3 / fmax((restTtiss3 + act0Ttiss3), 1.0));
double B1920tiss3_perml = (B1920tiss3 / Vtissue3);
double B19tiss3 = (B19no20tiss3 + B1920tiss3);
double B19tiss3_perml = (B19tiss3 / Vtissue3);
double BTrratio_pb = (Bpb / fmax((restTpb + act0Tpb), 1.0));
double BTrratio_tiss = (Btiss / fmax((restTtiss + act0Ttiss), 1.0));
double BTrratio_tiss2 = (Btiss2 / fmax((restTtiss2 + act0Ttiss2), 1.0));
double BTrratio_tumor = (Btumor / fmax((restTtumor + act0Ttumor), 1.0));
double Blinc_ngperml = 0.0;
double Blint2_ngperml = 0.0;
double Blint3_ngperml = 0.0;
double Blint_ngperml = 0.0;
double Blintumor_ngperml = 0.0;
double Bpb_perml = (Bpb / Vpb);
double Btiss2_perml = (Btiss2 / Vtissue2);
double Btiss_perml = (Btiss / Vtissue);
double Btumor_perml = (Btumor / Vtumor);
double IL6combo = (IL6pb + ((IL6_tiss_contribution * ((((IL6tiss * Vtissue) + (IL6tiss2 * Vtissue2)) + (IL6tiss3 * Vtissue3)) + (IL6tumor * Vtumor))) / Vpb));
double RTXc_ugperml = 0.0;
double RTXt2_ugperml = 0.0;
double RTXt3_ugperml = 0.0;
double RTXt_ugperml = 0.0;
double RTXtumor_ugperml = 0.0;
double TDBc_ugperml = ((((TDBc_ugperkg / Vc_tdb) > 1e-05) * TDBc_ugperkg) / Vc_tdb);
double TDBt2_ugperml = (Kp2 * TDBc_ugperml);
double TDBt3_ugperml = ((tissue3on * Kp3) * TDBc_ugperml);
double TDBt_ugperml = (Kp * TDBc_ugperml);
double TDBtumor_ugperml = ((tumor_on * Kptumor) * TDBc_ugperml);
double TaB1920ratio_tiss3 = (actTtiss3 / fmax(B1920tiss3, 1.0));
double TaB19ratio_tiss3 = (actTtiss3 / fmax(B19tiss3, 1.0));
double TaBratio_pb = (actTpb / fmax(Bpb, 1.0));
double TaBratio_tiss = (actTtiss / fmax(Btiss, 1.0));
double TaBratio_tiss2 = (actTtiss2 / fmax(Btiss2, 1.0));
double TaBratio_tumor = (actTtumor / fmax(Btumor, 1.0));
double act0Tpb_perml = (act0Tpb / Vpb);
double actTpb_perml = (actTpb / Vpb);
double drugBpbkill = (((VmB * pow(fmax(0.0, TaBratio_pb), nkill)) / (pow(fmax(0.0, KmTB_kill), nkill) + pow(fmax(0.0, TaBratio_pb), nkill))) * ((TDBc_ugperml * 1000.0) / (KdrugB + (TDBc_ugperml * 1000.0))));
double drugBtisskill = (((VmB * pow(fmax(0.0, TaBratio_tiss), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tiss), nkill))) * ((TDBt_ugperml * 1000.0) / (KdrugB + (TDBt_ugperml * 1000.0))));
double drugBtisskill2 = (((VmB * pow(fmax(0.0, TaBratio_tiss2), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tiss2), nkill))) * ((TDBt2_ugperml * 1000.0) / (KdrugB + (TDBt2_ugperml * 1000.0))));
double drugBtisskill3 = (((VmB * pow(fmax(0.0, TaB1920ratio_tiss3), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaB1920ratio_tiss3), nkill))) * ((TDBt3_ugperml * 1000.0) / (KdrugB + (TDBt3_ugperml * 1000.0))));
double drugBtumorkill = (((VmB * pow(fmax(0.0, TaBratio_tumor), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tumor), nkill))) * ((TDBtumor_ugperml * 1000.0) / (KdrugB + (TDBtumor_ugperml * 1000.0))));
double drugTpbact = ((VmT * (pow(BTrratio_pb, S) / (pow(KmBT_act, S) + pow(BTrratio_pb, S)))) * (pow((TDBc_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBc_ugperml * 1000.0), ndrugactT))));
double drugTtissact = (((fTact * VmT) * (pow(BTrratio_tiss, S) / (pow(KmBT_act, S) + pow(BTrratio_tiss, S)))) * (pow((TDBt_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt_ugperml * 1000.0), ndrugactT))));
double drugTtissact2 = (((fTact * VmT) * (pow(BTrratio_tiss2, S) / (pow(KmBT_act, S) + pow(BTrratio_tiss2, S)))) * (pow((TDBt2_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt2_ugperml * 1000.0), ndrugactT))));
double drugTtissact3 = (((fTact * VmT) * (pow(B1920Trratio_tiss3, S) / (pow(KmBT_act, S) + pow(B1920Trratio_tiss3, S)))) * (pow((TDBt3_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt3_ugperml * 1000.0), ndrugactT))));
double drugTtumoract = (((fTact * VmT) * (pow(fmax(BTrratio_tumor, 0.0), S) / (pow(KmBT_act, S) + pow(fmax(BTrratio_tumor, 0.0), S)))) * (pow((TDBtumor_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBtumor_ugperml * 1000.0), ndrugactT))));
double restTpb_perml = (restTpb / Vpb);
double totTpb_perml = ((restTpb_perml + act0Tpb_perml) + actTpb_perml);
double totTtiss = ((restTtiss + act0Ttiss) + actTtiss);
double totTtiss2 = ((restTtiss2 + act0Ttiss2) + actTtiss2);
double totTtiss3 = ((restTtiss3 + act0Ttiss3) + actTtiss3);
double B19Trratio_tiss3 = (B19tiss3 / fmax((restTtiss3 + act0Ttiss3), 1.0));
double BlinBpbkill = (((VmB * pow(fmax(0.0, TaBratio_pb), nkill_blin)) / (pow(fmax(0.0, KmTB_kill_blin), nkill_blin) + pow(fmax(0.0, TaBratio_pb), nkill_blin))) * (Blinc_ngperml / (KdrugB_blin + Blinc_ngperml)));
double BlinBtisskill = (((VmB * pow(fmax(0.0, TaBratio_tiss), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tiss), nkill_blin))) * (Blint_ngperml / (KdrugB_blin + Blint_ngperml)));
double BlinBtisskill2 = (((VmB * pow(fmax(0.0, TaBratio_tiss2), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tiss2), nkill_blin))) * (Blint2_ngperml / (KdrugB_blin + Blint2_ngperml)));
double BlinBtisskill3 = (((VmB * pow(fmax(0.0, TaB19ratio_tiss3), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaB19ratio_tiss3), nkill_blin))) * (Blint3_ngperml / (KdrugB_blin + Blint3_ngperml)));
double BlinBtumorkill = (((VmB * pow(fmax(0.0, TaBratio_tumor), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tumor), nkill_blin))) * (Blintumor_ngperml / (KdrugB_blin + Blintumor_ngperml)));
double BlinTpbact = ((VmT * (pow(BTrratio_pb, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_pb, S)))) * (pow(Blinc_ngperml, ndrugactT_blin) / (pow(Blinc_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
double BlinTtissact = (((fTact * VmT) * (pow(BTrratio_tiss, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_tiss, S)))) * (pow(Blint_ngperml, ndrugactT_blin) / (pow(Blint_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
double BlinTtissact2 = (((fTact * VmT) * (pow(BTrratio_tiss2, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_tiss2, S)))) * (pow(Blint2_ngperml, ndrugactT_blin) / (pow(Blint2_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
double BlinTtissact3 = (((fTact * VmT) * (pow(B19Trratio_tiss3, S) / (pow(KmBT_act_blin, S) + pow(B19Trratio_tiss3, S)))) * (pow(Blint3_ngperml, ndrugactT_blin) / (pow(Blint3_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
double BlinTtumoract = (((fTact * VmT) * (pow(fmax(BTrratio_tumor, 0.0), S) / (pow(KmBT_act_blin, S) + pow(fmax(BTrratio_tumor, 0.0), S)))) * (pow(Blintumor_ngperml, ndrugactT_blin) / (pow(Blintumor_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
double Bpb_norm = (Bpb_perml / Bpbref_perml);
double Tafraction_pb = (actTpb_perml / fmax(totTpb_perml, 1.0));
dxdt_Btiss = ((((kBprolif * KBp) * Bpbref_perml) * Vtissue) * pow(fmax(0.0, (1.0 - (Btiss / ((KBp * Bpbref_perml) * Vtissue)))), 1.0)) - ((((0.0 * fBprolif) * kBprolif) * Btiss) * kBapop_cll) + ((((tissue1on * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBp) - (Btiss / Vtissue)))) - (((fBkill * kBkill) * ((drugBtisskill + BlinBtisskill) + (RTXt_ugperml / ((Kmkill_rtx / 1000.0) + RTXt_ugperml)))) * Btiss);
dxdt_restTtiss = - (kTact * (((drugTtissact + BlinTtissact) * restTtiss) - (fTadeact * actTtiss))) + 0.0 + (((tissue1on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp) - (restTtiss / Vtissue))) + ((act0on * fTa0deact) * act0Ttiss) - ((((fapop_v24 * fTrapop) * kTaapop) * ((Trpbref_perml * Vtissue) * KTrp)) * fmax(0.0, ((restTtiss / ((Trpbref_perml * Vtissue) * KTrp)) - 1.0)));
dxdt_actTtiss = (kTact * (((drugTtissact + BlinTtissact) * restTtiss) - (fTadeact * actTtiss))) + (((tissue1on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp) * fTap) - (actTtiss / Vtissue))) + ((act0on * kTact) * (((drugTtissact + BlinTtissact) * act0Ttiss) - (fTadeact * actTtiss))) - ((fapop_v24 * kTaapop) * (actTtiss + ((fAICD * pow(actTtiss, 2.0)) / ((KTrp * Vtissue) * Trpbref_perml))));
dxdt_TDBc_ugperkg = - (((Cl_tdb + ((Vm_tdb / (Km_tdb + (TDBc_ugperkg / Vc_tdb))) / BW)) / Vc_tdb) * TDBc_ugperkg) - (Cld_tdb * ((TDBc_ugperkg / Vc_tdb) - (TDBp_ugperkg / Vp_tdb)));
dxdt_TDBp_ugperkg = (Cld_tdb * ((TDBc_ugperkg / Vc_tdb) - (TDBp_ugperkg / Vp_tdb)));
dxdt_restTpb = - (((tissue1on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp) - (restTtiss / Vtissue))) + (((kTgen * Vpb) * Trpbref_perml) * (fTgenbl + pow(fmax(0.0, (1.0 - (totTpb_perml / Trpbref_perml))), 2.0))) - (kTact * (((drugTpbact + BlinTpbact) * restTpb) - (fTadeact * actTpb))) - (((kTgen * fTgenbl) * restTpb) + ((fTrapop * kTaapop) * fmax(0.0, (restTpb - (Trpbref_perml * Vpb))))) + ((act0on * fTa0deact) * act0Tpb) - (((tissue2on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp2) - (restTtiss2 / Vtissue2))) - (((tissue3on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp3) - (restTtiss3 / Vtissue3))) - (((tumor_on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrptumor) - (restTtumor / Vtumor)));
dxdt_Bpb = - ((((tissue1on * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBp) - (Btiss / Vtissue)))) + ((((tissue3on * fBtissue3_v1) * kBapop) * Bpb) * kBapop_cll) - ((kBapop * Bpb) * kBapop_cll) - ((kBkill * ((drugBpbkill + BlinBpbkill) + (RTXc_ugperml / ((Kmkill_rtx / 1000.0) + RTXc_ugperml)))) * Bpb) - ((((tissue2on * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBp2) - (Btiss2 / Vtissue2)))) + ((((tissue3on * fBtissue3_v1) * kBtiss3exit) * Vpb) * fmax(0.0, ((B1920tiss3 / Vtissue3) - ((Bpb / Vpb) * KBp3)))) + ((((((tissue3on * fBtissue3_v1) * kBprolif) * kBapop_cll) * Bpbref_perml) * Vpb) * pow(fmax(0.0, (1.0 - (Bpb / (Bpbref_perml * Vpb)))), 1.0)) - (((((Bcell_tumor_trafficking_on * tumor_on) * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBptumor) - (Btumor / Vtumor))));
dxdt_actTpb = (kTact * (((drugTpbact + BlinTpbact) * restTpb) - (fTadeact * actTpb))) - (((tissue1on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp) * fTap) - (actTtiss / Vtissue))) - (kTaapop * (actTpb + ((fAICD * pow(actTpb, 2.0)) / (Vpb * Trpbref_perml)))) + ((act0on * kTact) * (((drugTpbact + BlinTpbact) * act0Tpb) - (fTadeact * actTpb))) - (((tissue2on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp2) * fTap) - (actTtiss2 / Vtissue2))) - (((tissue3on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp3) * fTap) - (actTtiss3 / Vtissue3))) - (((tumor_on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrptumor) * fTap) - (actTtumor / Vtumor)));
dxdt_act0Tpb = - ((act0on * fTa0deact) * act0Tpb) - ((act0on * kTact) * (((drugTpbact + BlinTpbact) * act0Tpb) - (fTadeact * actTpb))) - ((fTa0apop * kTaapop) * act0Tpb) - ((((tissue1on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp) - (act0Ttiss / Vtissue))) + (((act0on * fTaprolif) * kTprolif) * actTpb) - ((((tissue2on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp2) - (act0Ttiss2 / Vtissue2))) - ((((tissue3on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp3) - (act0Ttiss3 / Vtissue3))) - ((((tumor_on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrptumor) - (act0Ttumor / Vtumor)));
dxdt_act0Ttiss = - ((fTa0apop * kTaapop) * act0Ttiss) - ((act0on * kTact) * (((drugTtissact + BlinTtissact) * act0Ttiss) - (fTadeact * actTtiss))) - ((act0on * fTa0deact) * act0Ttiss) + ((((tissue1on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp) - (act0Ttiss / Vtissue))) + (((act0on * fTaprolif) * kTprolif) * actTtiss);
dxdt_injection_effect = - ((log(2.0) / tinjhalf) * injection_effect);
dxdt_act0Ttiss2 = (((act0on * fTaprolif) * kTprolif) * actTtiss2) + ((((tissue2on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp2) - (act0Ttiss2 / Vtissue2))) - ((act0on * fTa0deact) * act0Ttiss2) - ((act0on * kTact) * (((drugTtissact2 + BlinTtissact2) * act0Ttiss2) - (fTadeact * actTtiss2))) - ((fTa0apop * kTaapop) * act0Ttiss2);
dxdt_restTtiss2 = ((act0on * fTa0deact) * act0Ttiss2) + (((tissue2on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp2) - (restTtiss2 / Vtissue2))) - (kTact * (((drugTtissact2 + BlinTtissact2) * restTtiss2) - (fTadeact * actTtiss2))) - ((((fapop_v24 * fTrapop) * kTaapop) * ((Trpbref_perml * Vtissue2) * KTrp2)) * fmax(0.0, ((restTtiss2 / ((Trpbref_perml * Vtissue2) * KTrp2)) - 1.0)));
dxdt_actTtiss2 = ((act0on * kTact) * (((drugTtissact2 + BlinTtissact2) * act0Ttiss2) - (fTadeact * actTtiss2))) + (((tissue2on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp2) * fTap) - (actTtiss2 / Vtissue2))) + (kTact * (((drugTtissact2 + BlinTtissact2) * restTtiss2) - (fTadeact * actTtiss2))) - ((fapop_v24 * kTaapop) * (actTtiss2 + ((fAICD * pow(actTtiss2, 2.0)) / ((Vtissue2 * KTrp2) * Trpbref_perml))));
dxdt_Btiss2 = - (((fBkill * kBkill) * ((drugBtisskill2 + BlinBtisskill2) + (RTXt2_ugperml / ((Kmkill_rtx / 1000.0) + RTXt2_ugperml)))) * Btiss2) + ((((tissue2on * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBp2) - (Btiss2 / Vtissue2)))) - ((((0.0 * fBprolif) * kBprolif) * Btiss2) * kBapop_cll) + ((((kBprolif * KBp2) * Bpbref_perml) * Vtissue2) * pow(fmax(0.0, (1.0 - (Btiss2 / ((KBp2 * Bpbref_perml) * Vtissue2)))), 1.0));
dxdt_drug_effect = - ((log(2.0) / tinjhalf) * drug_effect);
dxdt_B19no20tiss3 = (((((Bpbref_perml * KBp3) * B19no20_B1920_ratio) * Vtissue3) * (kBapop + (kBapop / kBmat_kBapop_ratio))) * (1.0 + (5.0 * pow(fmax(0.0, (1.0 - (((Bpb + Btiss) + Btiss2) / (((Bpbref_perml * Vpb) + ((KBp * Bpbo_perml) * Vtissue)) + ((KBp2 * Bpbo_perml) * Vtissue2))))), 1.0)))) - ((kBapop / kBmat_kBapop_ratio) * B19no20tiss3) - ((kBapop * B19no20tiss3) * kBapop_cll) - (((fBkill * kBkill) * BlinBtisskill3) * B19no20tiss3) + (((((kBprolif * KBp3) * Bpbref_perml) * B19no20_B1920_ratio) * Vtissue3) * pow(fmax(0.0, (1.0 - (B19no20tiss3 / (((KBp3 * Bpbref_perml) * B19no20_B1920_ratio) * Vtissue3)))), 1.0));
dxdt_B1920tiss3 = ((kBapop / kBmat_kBapop_ratio) * B19no20tiss3) - ((((tissue3on * fBtissue3_v1) * kBtiss3exit) * Vpb) * fmax(0.0, ((B1920tiss3 / Vtissue3) - ((Bpb / Vpb) * KBp3)))) - ((kBapop * B1920tiss3) * kBapop_cll) - (((fBkill * kBkill) * ((drugBtisskill3 + BlinBtisskill3) + (RTXt3_ugperml / ((Kmkill_rtx / 1000.0) + RTXt3_ugperml)))) * B1920tiss3) + ((((kBprolif * KBp3) * Bpbref_perml) * Vtissue3) * pow(fmax(0.0, (1.0 - (B1920tiss3 / ((KBp3 * Bpbref_perml) * Vtissue3)))), 1.0));
dxdt_restTtiss3 = (((tissue3on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrp3) - (restTtiss3 / Vtissue3))) + ((act0on * fTa0deact) * act0Ttiss3) - (kTact * (((drugTtissact3 + BlinTtissact3) * restTtiss3) - (fTadeact * actTtiss3))) - ((((fapop_v24 * fTrapop) * kTaapop) * ((Trpbref_perml * Vtissue3) * KTrp3)) * fmax(0.0, ((restTtiss3 / ((Trpbref_perml * Vtissue3) * KTrp3)) - 1.0)));
dxdt_act0Ttiss3 = ((((tissue3on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrp3) - (act0Ttiss3 / Vtissue3))) - ((fTa0apop * kTaapop) * act0Ttiss3) - ((act0on * kTact) * (((drugTtissact3 + BlinTtissact3) * act0Ttiss3) - (fTadeact * actTtiss3))) - ((act0on * fTa0deact) * act0Ttiss3) + (((act0on * fTaprolif) * kTprolif) * actTtiss3);
dxdt_actTtiss3 = (((tissue3on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrp3) * fTap) - (actTtiss3 / Vtissue3))) + ((act0on * kTact) * (((drugTtissact3 + BlinTtissact3) * act0Ttiss3) - (fTadeact * actTtiss3))) + (kTact * (((drugTtissact3 + BlinTtissact3) * restTtiss3) - (fTadeact * actTtiss3))) - ((fapop_v24 * kTaapop) * (actTtiss3 + ((fAICD * pow(actTtiss3, 2.0)) / ((Vtissue3 * KTrp3) * Trpbref_perml))));
dxdt_restTtumor = ((act0on * fTa0deact) * act0Ttumor) - (kTact * (((drugTtumoract + BlinTtumoract) * restTtumor) - (fTadeact * actTtumor))) + (((tumor_on * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * restTpb) / Vpb) * KTrptumor) - (restTtumor / Vtumor))) - ((((fapop_v24 * fTrapop) * kTaapop) * ((Trpbref_perml * Vtumor) * KTrptumor)) * fmax(0.0, ((restTtumor / ((Trpbref_perml * Vtumor) * KTrptumor)) - 1.0)));
dxdt_act0Ttumor = - ((act0on * fTa0deact) * act0Ttumor) - ((act0on * kTact) * (((drugTtumoract + BlinTtumoract) * act0Ttumor) - (fTadeact * actTtumor))) + (((act0on * fTaprolif) * kTprolif) * actTtumor) + ((((tumor_on * act0on) * kTrexit) * Vpb) * ((((((1.0 + (finj * injection_effect)) + (fdrug * drug_effect)) * act0Tpb) / Vpb) * KTrptumor) - (act0Ttumor / Vtumor))) - ((fTa0apop * kTaapop) * act0Ttumor);
dxdt_actTtumor = ((act0on * kTact) * (((drugTtumoract + BlinTtumoract) * act0Ttumor) - (fTadeact * actTtumor))) + (kTact * (((drugTtumoract + BlinTtumoract) * restTtumor) - (fTadeact * actTtumor))) - ((fapop_v24 * kTaapop) * (actTtumor + ((fAICD * pow(actTtumor, 2.0)) / ((Vtumor * KTrptumor) * Trpbref_perml)))) + (((tumor_on * kTaexit) * Vpb) * ((((((1.0 + (fa0 * ((finj * injection_effect) + (fdrug * drug_effect)))) * actTpb) / Vpb) * KTrptumor) * fTap) - (actTtumor / Vtumor)));
dxdt_Btumor = ((kBtumorprolif * Btumor) + (((((0.0 * kBprolif) * KBptumor) * Bpbref_perml) * Vtumor) * pow(fmax(0.0, (1.0 - (Btumor / ((KBptumor * Bpbref_perml) * Vtumor)))), 1.0))) - (((0.0 * fBprolif) * kBprolif) * Btumor) - (((fBkill * kBkill) * ((drugBtumorkill + BlinBtumorkill) + (RTXtumor_ugperml / ((Kmkill_rtx / 1000.0) + RTXtumor_ugperml)))) * Btumor) + (((((Bcell_tumor_trafficking_on * tumor_on) * fBexit) * kTaexit) * Vpb) * fmax(0.0, (((Bpb / Vpb) * KBptumor) - (Btumor / Vtumor))));
dxdt_IL6pb = ((((kIL6prod * actTpb) / Vpb) * (Bpb_perml / Bpbref_perml)) * ((pow((TDBc_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBc_ugperml * 1000.0), ndrugactT))) + (pow(Blinc_ngperml, ndrugactT_blin) / (pow(Blinc_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))))) - ((log(2.0) / ((thalfIL6 / 60.0) / 24.0)) * IL6pb);
dxdt_IL6tiss = ((((kIL6prod * actTtiss) / Vtissue) * (Btiss_perml / (Bpbref_perml * KBp))) * ((pow((TDBt_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt_ugperml * 1000.0), ndrugactT))) + (pow(Blint_ngperml, ndrugactT_blin) / (pow(Blint_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))))) - ((log(2.0) / ((thalfIL6 / 60.0) / 24.0)) * IL6tiss);
dxdt_IL6tiss2 = ((((kIL6prod * actTtiss2) / Vtissue2) * (Btiss2_perml / (Bpbref_perml * KBp2))) * ((pow((TDBt2_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt2_ugperml * 1000.0), ndrugactT))) + (pow(Blint2_ngperml, ndrugactT_blin) / (pow(Blint2_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))))) - ((log(2.0) / ((thalfIL6 / 60.0) / 24.0)) * IL6tiss2);
dxdt_IL6tiss3 = (((kIL6prod * actTtiss3) / Vtissue3) * (((B1920tiss3_perml / (Bpbref_perml * KBp3)) * (pow((TDBt3_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt3_ugperml * 1000.0), ndrugactT)))) + ((B19tiss3_perml / ((Bpbref_perml * KBp3) * (1.0 + B19no20_B1920_ratio))) * (pow(Blint3_ngperml, ndrugactT_blin) / (pow(Blint3_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin)))))) - ((log(2.0) / ((thalfIL6 / 60.0) / 24.0)) * IL6tiss3);
dxdt_IL6tumor = ((((kIL6prod * actTtumor) / Vtumor) * (Btumor_perml / (Bpbref_perml * KBptumor))) * ((pow((TDBtumor_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBtumor_ugperml * 1000.0), ndrugactT))) + (pow(Blintumor_ngperml, ndrugactT_blin) / (pow(Blintumor_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))))) - ((log(2.0) / ((thalfIL6 / 60.0) / 24.0)) * IL6tumor);

$TABLE
B1920Trratio_tiss3 = (B1920tiss3 / fmax((restTtiss3 + act0Ttiss3), 1.0));
B1920tiss3_perml = (B1920tiss3 / Vtissue3);
B19tiss3 = (B19no20tiss3 + B1920tiss3);
B19tiss3_perml = (B19tiss3 / Vtissue3);
BTrratio_pb = (Bpb / fmax((restTpb + act0Tpb), 1.0));
BTrratio_tiss = (Btiss / fmax((restTtiss + act0Ttiss), 1.0));
BTrratio_tiss2 = (Btiss2 / fmax((restTtiss2 + act0Ttiss2), 1.0));
BTrratio_tumor = (Btumor / fmax((restTtumor + act0Ttumor), 1.0));
Blinc_ngperml = 0.0;
Blint2_ngperml = 0.0;
Blint3_ngperml = 0.0;
Blint_ngperml = 0.0;
Blintumor_ngperml = 0.0;
Bpb_perml = (Bpb / Vpb);
Btiss2_perml = (Btiss2 / Vtissue2);
Btiss_perml = (Btiss / Vtissue);
Btumor_perml = (Btumor / Vtumor);
IL6combo = (IL6pb + ((IL6_tiss_contribution * ((((IL6tiss * Vtissue) + (IL6tiss2 * Vtissue2)) + (IL6tiss3 * Vtissue3)) + (IL6tumor * Vtumor))) / Vpb));
RTXc_ugperml = 0.0;
RTXt2_ugperml = 0.0;
RTXt3_ugperml = 0.0;
RTXt_ugperml = 0.0;
RTXtumor_ugperml = 0.0;
TDBc_ugperml = ((((TDBc_ugperkg / Vc_tdb) > 1e-05) * TDBc_ugperkg) / Vc_tdb);
TDBt2_ugperml = (Kp2 * TDBc_ugperml);
TDBt3_ugperml = ((tissue3on * Kp3) * TDBc_ugperml);
TDBt_ugperml = (Kp * TDBc_ugperml);
TDBtumor_ugperml = ((tumor_on * Kptumor) * TDBc_ugperml);
TaB1920ratio_tiss3 = (actTtiss3 / fmax(B1920tiss3, 1.0));
TaB19ratio_tiss3 = (actTtiss3 / fmax(B19tiss3, 1.0));
TaBratio_pb = (actTpb / fmax(Bpb, 1.0));
TaBratio_tiss = (actTtiss / fmax(Btiss, 1.0));
TaBratio_tiss2 = (actTtiss2 / fmax(Btiss2, 1.0));
TaBratio_tumor = (actTtumor / fmax(Btumor, 1.0));
act0Tpb_perml = (act0Tpb / Vpb);
actTpb_perml = (actTpb / Vpb);
drugBpbkill = (((VmB * pow(fmax(0.0, TaBratio_pb), nkill)) / (pow(fmax(0.0, KmTB_kill), nkill) + pow(fmax(0.0, TaBratio_pb), nkill))) * ((TDBc_ugperml * 1000.0) / (KdrugB + (TDBc_ugperml * 1000.0))));
drugBtisskill = (((VmB * pow(fmax(0.0, TaBratio_tiss), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tiss), nkill))) * ((TDBt_ugperml * 1000.0) / (KdrugB + (TDBt_ugperml * 1000.0))));
drugBtisskill2 = (((VmB * pow(fmax(0.0, TaBratio_tiss2), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tiss2), nkill))) * ((TDBt2_ugperml * 1000.0) / (KdrugB + (TDBt2_ugperml * 1000.0))));
drugBtisskill3 = (((VmB * pow(fmax(0.0, TaB1920ratio_tiss3), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaB1920ratio_tiss3), nkill))) * ((TDBt3_ugperml * 1000.0) / (KdrugB + (TDBt3_ugperml * 1000.0))));
drugBtumorkill = (((VmB * pow(fmax(0.0, TaBratio_tumor), nkill)) / (pow(fmax(0.0, (KmTB_kill * fKmTB_kill)), nkill) + pow(fmax(0.0, TaBratio_tumor), nkill))) * ((TDBtumor_ugperml * 1000.0) / (KdrugB + (TDBtumor_ugperml * 1000.0))));
drugTpbact = ((VmT * (pow(BTrratio_pb, S) / (pow(KmBT_act, S) + pow(BTrratio_pb, S)))) * (pow((TDBc_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBc_ugperml * 1000.0), ndrugactT))));
drugTtissact = (((fTact * VmT) * (pow(BTrratio_tiss, S) / (pow(KmBT_act, S) + pow(BTrratio_tiss, S)))) * (pow((TDBt_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt_ugperml * 1000.0), ndrugactT))));
drugTtissact2 = (((fTact * VmT) * (pow(BTrratio_tiss2, S) / (pow(KmBT_act, S) + pow(BTrratio_tiss2, S)))) * (pow((TDBt2_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt2_ugperml * 1000.0), ndrugactT))));
drugTtissact3 = (((fTact * VmT) * (pow(B1920Trratio_tiss3, S) / (pow(KmBT_act, S) + pow(B1920Trratio_tiss3, S)))) * (pow((TDBt3_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBt3_ugperml * 1000.0), ndrugactT))));
drugTtumoract = (((fTact * VmT) * (pow(fmax(BTrratio_tumor, 0.0), S) / (pow(KmBT_act, S) + pow(fmax(BTrratio_tumor, 0.0), S)))) * (pow((TDBtumor_ugperml * 1000.0), ndrugactT) / (pow(KdrugactT, ndrugactT) + pow((TDBtumor_ugperml * 1000.0), ndrugactT))));
restTpb_perml = (restTpb / Vpb);
totTpb_perml = ((restTpb_perml + act0Tpb_perml) + actTpb_perml);
totTtiss = ((restTtiss + act0Ttiss) + actTtiss);
totTtiss2 = ((restTtiss2 + act0Ttiss2) + actTtiss2);
totTtiss3 = ((restTtiss3 + act0Ttiss3) + actTtiss3);
B19Trratio_tiss3 = (B19tiss3 / fmax((restTtiss3 + act0Ttiss3), 1.0));
BlinBpbkill = (((VmB * pow(fmax(0.0, TaBratio_pb), nkill_blin)) / (pow(fmax(0.0, KmTB_kill_blin), nkill_blin) + pow(fmax(0.0, TaBratio_pb), nkill_blin))) * (Blinc_ngperml / (KdrugB_blin + Blinc_ngperml)));
BlinBtisskill = (((VmB * pow(fmax(0.0, TaBratio_tiss), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tiss), nkill_blin))) * (Blint_ngperml / (KdrugB_blin + Blint_ngperml)));
BlinBtisskill2 = (((VmB * pow(fmax(0.0, TaBratio_tiss2), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tiss2), nkill_blin))) * (Blint2_ngperml / (KdrugB_blin + Blint2_ngperml)));
BlinBtisskill3 = (((VmB * pow(fmax(0.0, TaB19ratio_tiss3), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaB19ratio_tiss3), nkill_blin))) * (Blint3_ngperml / (KdrugB_blin + Blint3_ngperml)));
BlinBtumorkill = (((VmB * pow(fmax(0.0, TaBratio_tumor), nkill_blin)) / (pow(fmax(0.0, (KmTB_kill_blin * fKmTB_kill)), nkill_blin) + pow(fmax(0.0, TaBratio_tumor), nkill_blin))) * (Blintumor_ngperml / (KdrugB_blin + Blintumor_ngperml)));
BlinTpbact = ((VmT * (pow(BTrratio_pb, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_pb, S)))) * (pow(Blinc_ngperml, ndrugactT_blin) / (pow(Blinc_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
BlinTtissact = (((fTact * VmT) * (pow(BTrratio_tiss, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_tiss, S)))) * (pow(Blint_ngperml, ndrugactT_blin) / (pow(Blint_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
BlinTtissact2 = (((fTact * VmT) * (pow(BTrratio_tiss2, S) / (pow(KmBT_act_blin, S) + pow(BTrratio_tiss2, S)))) * (pow(Blint2_ngperml, ndrugactT_blin) / (pow(Blint2_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
BlinTtissact3 = (((fTact * VmT) * (pow(B19Trratio_tiss3, S) / (pow(KmBT_act_blin, S) + pow(B19Trratio_tiss3, S)))) * (pow(Blint3_ngperml, ndrugactT_blin) / (pow(Blint3_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
BlinTtumoract = (((fTact * VmT) * (pow(fmax(BTrratio_tumor, 0.0), S) / (pow(KmBT_act_blin, S) + pow(fmax(BTrratio_tumor, 0.0), S)))) * (pow(Blintumor_ngperml, ndrugactT_blin) / (pow(Blintumor_ngperml, ndrugactT_blin) + pow(KdrugactT_blin, ndrugactT_blin))));
Bpb_norm = (Bpb_perml / Bpbref_perml);
Tafraction_pb = (actTpb_perml / fmax(totTpb_perml, 1.0));

$CAPTURE TDBc_ugperml Bpb_perml totTpb_perml Tafraction_pb IL6combo Btiss_perml Btiss2_perml B1920tiss3_perml Bpb_norm Btumor_perml
